// react/src/plugins/site/Install.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import { Form } from 'semantic-ui-react'
import { FormattedMessage } from 'react-intl'
import { push } from 'react-router-redux'
import { connect } from 'react-redux'

import Layout from '../auth/NonSignIn'
import {Submit} from '../../form'
import {post} from '../../ajax'

class Widget extends Component{
  state = { title: '', subTitle: '', name: '', email: '', password: '', passwordConfirmation: '' }

  handleChange = (e, { name, value }) => this.setState({ [name]: value })

  handleSubmit = e => {
    e.preventDefault()
    const {push} = this.props
    var data = new URLSearchParams()
    data.append('title',this.state.title)
    data.append('subTitle',this.state.subTitle)
    data.append('name',this.state.name)
    data.append('email',this.state.email)
    data.append('password',this.state.password)
    data.append('passwordConfirmation',this.state.passwordConfirmation)
    post('/users/sign-up', data).then((rst) => {
      push('/users/sign-in')
    }).catch(alert)
  }
  render() {
    const {title, subTitle, name, email, password, passwordConfirmation} = this.state;
    return (
      <Layout title="site.install.title">
        <Form onSubmit={this.handleSubmit}>
          <Form.Input name='title' value={title} onChange={this.handleChange}  required label={<FormattedMessage id="site.attributes.title"/>} />
          <Form.Input name='subTitle' value={subTitle} onChange={this.handleChange} required label={<FormattedMessage id="site.attributes.subTitle"/>} />
          <Form.Input name='name' value={name} onChange={this.handleChange} required label={<FormattedMessage id="attributes.fullName"/>} />
          <Form.Input name='email' value={email} onChange={this.handleChange} required type="email" label={<FormattedMessage id="attributes.email"/>} />
          <Form.Input name='password' value={password} onChange={this.handleChange} required type="password" label={<FormattedMessage id="attributes.password"/>} />
          <Form.Input name='passwordConfirmation' value={passwordConfirmation} onChange={this.handleChange} required type="password" label={<FormattedMessage id="attributes.passwordConfirmation"/>} />
          <Submit />
        </Form>
      </Layout>
    )
  }
}


Widget.propTypes = {
  push: PropTypes.func.isRequired
}


export default connect(
  state => ({}),
  {push},
)(Widget)

// dashboard/src/plugins/site/Install.vue
<template>
  <non-sign-in-layout title="site.install.title">
    <form>
      <div class="form-group">
        <label for="title">{{$t('site.attributes.title')}}</label>
        <input v-model="title" type="text" class="form-control" id="title" />
      </div>
      <div class="form-group">
        <label for="subTitle">{{$t('site.attributes.subTitle')}}</label>
        <input v-model="subTitle" type="text" class="form-control" id="subTitle" />
      </div>
      <div class="form-group">
        <label for="email">{{$t('attributes.email')}}</label>
        <input v-model="email" type="email" class="form-control" id="email" aria-describedby="emailHelp">
        <small id="emailHelp" class="form-text text-muted">{{$t('helpers.email')}}</small>
      </div>
      <div class="form-group">
        <label for="password">{{$t('attributes.password')}}</label>
        <input v-model="password" type="password" class="form-control" id="password" aria-describedby="passwordHelp"/>
        <small id="passwordHelp" class="form-text text-muted">{{$t('helpers.password')}}</small>
      </div>
      <div class="form-group">
        <label for="passwordConfirmation">{{$t('attributes.passwordConfirmation')}}</label>
        <input v-model="passwordConfirmation" type="password" class="form-control" id="passwordConfirmation" aria-describedby="passwordConfirmationHelp" />
        <small id="passwordConfirmationHelp" class="form-text text-muted">{{$t('helpers.passwordConfirmation')}}</small>
      </div>
      <button v-on:click="onSubmit" type="submit" class="btn btn-primary">{{$t('buttons.submit')}}</button>
    </form>
  </non-sign-in-layout>
</template>

<script>
import {post} from '@/ajax'

export default {
  data () {
    return {
      title: '',
      subTitle: '',
      email: '',
      password: '',
      passwordConfirmation: ''
    }
  },
  methods: {
    onSubmit (e) {
      e.preventDefault()
      post(
        '/install',
        {
          title: this.title,
          subTitle: this.subTitle,
          email: this.email,
          password: this.password,
          passwordConfirmation: this.passwordConfirmation
        },
        function (rst) {
          alert(this.$t('success'))
          this.$router.push({name: 'auth.users.sign-in'})
        }.bind(this)
      )
    }
  }
}
</script>
