// react/src/layouts/Application.jsx
import React from 'react'
import PropTypes from 'prop-types'

import Header from '../components/Header'
import Footer from '../components/Footer'

const Widget = ({children}) => (
  <div>
    <Header />
    <div className="container">
      <div className="row">
        {children}        
      </div>
      <hr />
      <Footer />
    </div>
  </div>
)

Widget.propTypes = {
  children: PropTypes.node.isRequired
}

export default Widget

// vue/src/layouts/Application.vue
<template>
  <div>
    <app-header />
    <el-row>
      <slot />
    </el-row>
    <hr />
    <app-footer />
  </div>
</template>

<script>
import Header from '@/components/Header'
import Footer from '@/components/Footer'

export default {
  data () {
    return {
    }
  },
  components: {
    'app-header': Header,
    'app-footer': Footer
  }
}
</script>
