// react/src/plugins/auth/NonSignIn.jsx
import React from 'react'
import PropTypes from 'prop-types'
import {Grid, Header, Divider, List} from 'semantic-ui-react'
import {FormattedMessage} from 'react-intl'
import {Link} from 'react-router-dom'

import Layout from '../../layouts/Application'
import {NonSignInLinks} from '../../constants'

const Widget = ({title, children}) => (
  <Layout>
    <Grid.Row centered columns={2}>
      <Grid.Column>
        <Header><FormattedMessage id={title}/></Header>
        <Divider />
        {children}
        <br />
        <List>
          {
            NonSignInLinks.map((l, i) => <List.Item as={Link} to={l.href} key={i} icon={l.icon} content={<FormattedMessage id={l.label} />} />)
          }
        </List>
      </Grid.Column>
    </Grid.Row>
  </Layout>
)

Widget.propTypes = {
  title: PropTypes.string.isRequired,
  children: PropTypes.node.isRequired
}

export default Widget

// vue/src/layouts/NonSignIn.vue
<template>
  <application-layout>
    <el-col :span="12" :offset="6">
      <h2>{{$t(title)}}</h2>
      <hr />
      <slot />
      <ul class="list-group">
        <li class="list-group-item" v-if="l" v-for="(l, i) in links" :key="i">
          <fa-icon :name="l.icon" />&nbsp;
          <router-link :to="{name: l.href}">
            {{$t(`${l.href}.title`)}}
          </router-link>
        </li>
      </ul>
    </el-col>
  </application-layout>
</template>

<script>
import {nonSignInLinks as links} from '@/constants'

export default {
  props: ['title'],
  data () {
    return {
      links
    }
  }
}
</script>
